$ANSIBLE_VAULT;1.1;AES256
32363364306636386166316161373064386464316230363035356632343565666465373864346339
3934323065633163303738323935653933373761353763390a666139326133646665626666663736
35663961343566336435313735636361363139376332316430303137633930656436316461383962
3137316161306235340a326231373762646333656430363734383565373535343731343464613931
62666361333964653030383765326134653461356337663465306335306136376436663335396462
36303161376563643533366637393330336461613562366662376132636332306366366266303533
66306538643265323036636433333937356136393263343834303230386461633964336138373863
63303065393535663366633931326532313030386433323430333838346162346566336631663263
64373136623739336234353362346333356336316133316431643765623535623737373262393138
33623035666539363137353838346130313339326637633862333032343235316465623364313036
32616261303535643032646437313035626437323165343331363437656632343030353133343031
65626533376434613538383635373236633339623830646262363761633932303234333732313235
31313937373963656265633135346261363431316439306336373162376139323932633263666539
38306534663831373162313366393564653632663833333931323730653234663064343234653835
65386661646537663534343764653966326433613333383132373238396363363936376539326235
37336665316464343137
